package raptor.swt.chess.controller;

public enum ToolBarItemKey {
	LAST_NAV, NEXT_NAV, BACK_NAV, FIRST_NAV, COMMIT_NAV, REVERT_NAV, AUTO_QUEEN, AUTO_ROOK, AUTO_BISHOP, AUTO_KNIGHT, AUTO_DRAW, FLIP, SETUP_DONE, SETUP_START, SETUP_CLEAR, SETUP_FROM_FEN, CLEAR_PREMOVES, FEN
}